apiVersion: v1
kind: ServiceAccount
metadata:
  name: skupper-network-observer
  labels:
    app: skupper-network-observer
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.primary: >
      {"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"skupper-network-observer"}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skupper-network-observer-nginx
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;
    error_log  /dev/stderr warn;
    pid        /tmp/nginx.pid;

    events {
      worker_connections  1024;
    }

    http {
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  /dev/stdout  main;

      sendfile        on;
      keepalive_timeout  65;

      server {
          listen       8080;
          server_name  localhost;

          location / {
              root   /usr/share/nginx/html;
              index  index.html index.htm;
          }

          location /api/ {
              proxy_pass http://localhost:9090/;
          }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: skupper-network-observer-prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'skupper-network-observer'
        static_configs:
          - targets: ['localhost:9090']
---
apiVersion: v1
kind: Service
metadata:
  name: skupper-network-observer
  labels:
    app: skupper-network-observer
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: skupper-network-observer-tls
spec:
  selector:
    app: skupper-network-observer
  ports:
    - name: https
      port: 443
      targetPort: 8443
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-network-observer
  labels:
    app: skupper-network-observer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skupper-network-observer
  template:
    metadata:
      labels:
        app: skupper-network-observer
    spec:
      serviceAccountName: skupper-network-observer
      containers:
        - name: observer
          image: registry.redhat.io/service-interconnect/skupper-network-observer-rhel9:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9090
          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            - name: prom-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: client-cert
              mountPath: /etc/skupper-network-observer/certs/client
            - name: router-ca
              mountPath: /etc/skupper-network-observer/certs/ca
        - name: proxy
          image: registry.redhat.io/openshift4/ose-oauth-proxy:latest
          args:
            - --https-address=:8443
            - --provider=openshift
            - --upstream=http://127.0.0.1:8080
            - --tls-cert=/etc/tls/private/tls.crt
            - --tls-key=/etc/tls/private/tls.key
            - --cookie-secret-file=/etc/oauth/config/cookie_secret
            - --openshift-service-account=skupper-network-observer
            - --openshift-sar={"namespace":"rhsi","resource":"pods","verb":"get"}
          ports:
            - containerPort: 8443
              name: public
          volumeMounts:
            - name: oauth-config
              mountPath: /etc/oauth/config
            - name: tls-cert
              mountPath: /etc/tls/private
        - name: prometheus
          image: registry.redhat.io/openshift4/ose-prometheus:latest
          args:
            - --config.file=/etc/prometheus/prometheus.yml
            - --storage.tsdb.path=/prometheus
          ports:
            - containerPort: 9091
              name: prometheus
          volumeMounts:
            - name: prom-config
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
            - name: prom-data
              mountPath: /prometheus
      volumes:
        - name: nginx-config
          configMap:
            name: skupper-network-observer-nginx
        - name: prom-config
          configMap:
            name: skupper-network-observer-prometheus
        - name: prom-data
          emptyDir: {}
        - name: oauth-config
          emptyDir: {}
        - name: tls-cert
          secret:
            secretName: skupper-network-observer-tls
        - name: client-cert
          secret:
            secretName: skupper-network-observer-client
        - name: router-ca
          configMap:
            name: skupper-local-ca
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: skupper-network-observer
  labels:
    app: skupper-network-observer
spec:
  to:
    kind: Service
    name: skupper-network-observer
  tls:
    termination: reencrypt
---
apiVersion: skupper.io/v2alpha1
kind: Certificate
metadata:
  name: skupper-network-observer-client
spec:
  ca: skupper-local-ca
  client: true
  hosts:
    - skupper-router-local
  subject: skupper-router-local
