apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-external-sesecrets-operator
  namespace: external-secrets-operator
spec:
  channel: tech-preview-v0.1
  name: openshift-external-secrets-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic
