apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-external-secrets-operator
  namespace: external-secrets-operator
spec:
  # Empty targetNamespaces means: watch all namespaces in the cluster
  targetNamespaces: []
