apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: rhsi-edb-operator-pullsecret
  namespace: rhsi
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rhsi-edb-operator-pullsecret
  namespace: rhsi
subjects:
- kind: ServiceAccount
  name: rhsi-vault-reader
  namespace: rhsi
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: rhsi-edb-operator-pullsecret
