apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: edb-repos2-token
  namespace: rhsi
spec:
  secretStoreRef:
    kind: SecretStore
    name: vault-rhsi
  refreshInterval: 1h
  target:
    name: edb-repos2-token
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: token
    remoteRef:
      key: edb-repos2
      property: token
