apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: edb-repos2-token
  namespace: rhsi
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: vault-rhsi
  target:
    name: edb-repos2-token
    creationPolicy: Owner
  data:
    - secretKey: token
      remoteRef:
        key: edb-repos2
        property: token

