apiVersion: batch/v1
kind: Job
metadata:
  name: create-access-token-from-vault
  namespace: rhsi
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: rhsi-vault-reader
      restartPolicy: Never
      volumes:
      - name: link-token
        secret:
          secretName: rhsi-link-token
      containers:
      - name: debug
        image: registry.access.redhat.com/ubi9/ubi-minimal
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "[create-access-token-from-vault] Stub job running..."
          echo "Mounted rhsi-link-token contents:"
          ls -l /link-token || true
          for f in ca code url; do
            if [ -f "/link-token/$f" ]; then
              echo "--- $f ---"
              cat "/link-token/$f"
              echo
            fi
          done
          echo
          echo "TODO: replace this script with logic that redeems the AccessGrant"
          echo "and creates/updates the 'skupper-access-token-from-vault' Secret."
        volumeMounts:
        - name: link-token
          mountPath: /link-token
