apiVersion: batch/v1
kind: Job
metadata:
  name: create-access-token-from-vault
  namespace: rhsi
  labels:
    app.kubernetes.io/instance: rhsi-standby-site-b
spec:
  backoffLimit: 6
  template:
    metadata:
      name: create-access-token-from-vault
    spec:
      serviceAccountName: rhsi-vault-reader
      restartPolicy: Never
      containers:
        - name: create-access-token
          image: registry.redhat.io/openshift4/ose-cli:latest
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail

              NS="${NAMESPACE:-rhsi}"

              echo "=== DEBUG: Cluster identity from inside the job ==="
              oc whoami --show-server || echo "oc whoami --show-server failed"
              oc whoami || echo "oc whoami failed"
              echo "Namespace (downward API): ${NS}"
              echo "=================================================="

              echo "Waiting for Secret rhsi-link-token to exist in namespace ${NS}..."
              for i in {1..60}; do
                if oc -n "${NS}" get secret rhsi-link-token >/dev/null 2>&1; then
                  echo "Secret rhsi-link-token found."
                  break
                fi
                echo "  still waiting... (${i})"
                sleep 5
              done

              if ! oc -n "${NS}" get secret rhsi-link-token >/dev/null 2>&1; then
                echo "ERROR: Secret rhsi-link-token did not appear within timeout."
                exit 1
              fi

              echo "Reading AccessToken fields from Secret rhsi-link-token..."
              CODE=$(oc -n "${NS}" get secret rhsi-link-token -o jsonpath='{.data.code}' | base64 -d)
              URL=$(oc -n "${NS}" get secret rhsi-link-token -o jsonpath='{.data.url}' | base64 -d)
              CA=$(oc -n "${NS}" get secret rhsi-link-token -o jsonpath='{.data.ca}' | base64 -d)

              echo "DEBUG: Current AccessTokens in ${NS} BEFORE apply:"
              oc -n "${NS}" get accesstoken 2>/dev/null || echo "  (none or no permission)"

              echo "Creating AccessToken standby-from-vault in ${NS}..."
              APPLY_OUTPUT=$(
                {
                  echo "apiVersion: skupper.io/v2alpha1"
                  echo "kind: AccessToken"
                  echo "metadata:"
                  echo "  name: standby-from-vault"
                  echo "  namespace: ${NS}"
                  echo "spec:"
                  echo "  code: \"${CODE}\""
                  echo "  url: \"${URL}\""
                  echo "  ca: |"
                  echo "${CA}" | sed 's/^/    /'
                } | oc apply -f - 2>&1
              ) || {
                echo "ERROR: oc apply for AccessToken failed:"
                echo "${APPLY_OUTPUT}"
                exit 1
              }

              echo "oc apply output:"
              echo "${APPLY_OUTPUT}"

              echo "DEBUG: AccessTokens in ${NS} IMMEDIATELY AFTER apply:"
              oc -n "${NS}" get accesstoken 2>/dev/null || echo "  (none or no permission)"

              echo "Sleeping 10s and listing again to see if the controller deletes it quickly..."
              sleep 10
              echo "DEBUG: AccessTokens in ${NS} 10s AFTER apply:"
              oc -n "${NS}" get accesstoken 2>/dev/null || echo "  (still none or no permission)"

              echo "Job complete: AccessToken standby-from-vault creation flow finished."
