apiVersion: batch/v1
kind: Job
metadata:
  name: create-access-token-from-vault
  namespace: rhsi
spec:
  template:
    metadata:
      name: create-access-token-from-vault
    spec:
      serviceAccountName: rhsi-vault-reader
      restartPolicy: Never
      containers:
        - name: create-access-token
          image: registry.access.redhat.com/ubi9/ubi-minimal:latest
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail

              microdnf install -y kubernetes-client

              CODE=$(kubectl -n rhsi get secret rhsi-link-token -o jsonpath='{.data.code}' | base64 -d)
              URL=$(kubectl -n rhsi get secret rhsi-link-token -o jsonpath='{.data.url}' | base64 -d)
              CA=$(kubectl -n rhsi get secret rhsi-link-token -o jsonpath='{.data.ca}' | base64 -d)

              # Indent the CA certificate so it is valid YAML under "ca: |"
              CA_INDENTED=$(printf '%s\n' "${CA}" | sed 's/^/                /')

              cat << EOF | kubectl apply -f -
              apiVersion: skupper.io/v2alpha1
              kind: AccessToken
              metadata:
                name: standby-from-vault
                namespace: rhsi
              spec:
                code: "${CODE}"
                url: "${URL}"
                ca: |
${CA_INDENTED}
              EOF