apiVersion: batch/v1
kind: Job
metadata:
  name: create-access-token-from-vault
  namespace: rhsi
spec:
  backoffLimit: 6
  template:
    metadata:
      name: create-access-token-from-vault
    spec:
      serviceAccountName: rhsi-vault-reader
      restartPolicy: Never
      containers:
        - name: create-access-token
          image: registry.redhat.io/openshift4/ose-cli
          imagePullPolicy: IfNotPresent
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          command:
            - /bin/bash
            - -c
            - |
              set -euo pipefail

              SECRET_NAME="rhsi-link-token"
              NAMESPACE="${NAMESPACE:-rhsi}"

              echo "Waiting for Secret ${SECRET_NAME} to exist..."
              until oc get secret "${SECRET_NAME}" -n "${NAMESPACE}" >/dev/null 2>&1; do
                echo "Secret ${SECRET_NAME} not found yet. Sleeping 5s..."
                sleep 5
              done

              echo "Secret ${SECRET_NAME} found."
              echo "Reading AccessToken fields from Secret ${SECRET_NAME}..."

              CODE=$(oc get secret "${SECRET_NAME}" -n "${NAMESPACE}" -o jsonpath='{.data.code}' | base64 -d)
              URL=$(oc get secret "${SECRET_NAME}" -n "${NAMESPACE}" -o jsonpath='{.data.url}' | base64 -d)
              CA=$(oc get secret "${SECRET_NAME}" -n "${NAMESPACE}" -o jsonpath='{.data.ca}' | base64 -d)

              echo "Creating AccessToken standby-from-vault..."
              {
                echo "apiVersion: skupper.io/v2alpha1"
                echo "kind: AccessToken"
                echo "metadata:"
                echo "  name: standby-from-vault"
                echo "  namespace: ${NAMESPACE}"
                echo "spec:"
                echo "  code: \"${CODE}\""
                echo "  url: \"${URL}\""
                echo "  ca: |"
                echo "${CA}" | sed 's/^/    /'
              } | oc apply -f -

              echo "AccessToken standby-from-vault created/updated."
