apiVersion: batch/v1
kind: Job
metadata:
  name: create-edb-operator-pullsecret-from-vault
  namespace: rhsi
spec:
  backoffLimit: 6
  template:
    metadata:
      name: create-edb-operator-pullsecret-from-vault
    spec:
      serviceAccountName: rhsi-vault-reader
      restartPolicy: Never
      containers:
        - name: create-edb-operator-pullsecret
          image: registry.redhat.io/openshift4/ose-cli:latest
          command:
            - /bin/bash
            - -c
          args:
            - |
              set -euo pipefail

              echo "Waiting for Secret edb-repos2-token to exist in namespace rhsi..."
              for i in {1..60}; do
                if oc -n rhsi get secret edb-repos2-token >/dev/null 2>&1; then
                  echo "Secret edb-repos2-token found."
                  break
                fi
                echo "  still waiting... (${i})"
                sleep 5
              done

              if ! oc -n rhsi get secret edb-repos2-token >/dev/null 2>&1; then
                echo "ERROR: Secret edb-repos2-token did not appear within timeout."
                exit 1
              fi

              echo "Reading EDB token from Secret edb-repos2-token..."
              EDB_TOKEN=$(oc -n rhsi get secret edb-repos2-token -o jsonpath='{.data.token}' | base64 -d)

              echo "Creating/Updating docker-registry Secret postgresql-operator-pull-secret in openshift-operators..."
              oc -n openshift-operators create secret docker-registry postgresql-operator-pull-secret \
                --docker-server=docker.enterprisedb.com \
                --docker-username=k8s \
                --docker-password="${EDB_TOKEN}" \
                --dry-run=client -o yaml | oc apply -f -

              echo "Secret postgresql-operator-pull-secret created/updated successfully."

