apiVersion: batch/v1
kind: Job
metadata:
  name: create-edb-operator-pullsecret-from-vault
  namespace: rhsi
spec:
  backoffLimit: 1
  template:
    spec:
      serviceAccountName: rhsi-vault-reader
      restartPolicy: Never
      volumes:
      - name: edb-token
        secret:
          secretName: edb-repos2-token
      containers:
      - name: debug
        image: registry.access.redhat.com/ubi9/ubi-minimal
        command:
        - /bin/sh
        - -c
        - |
          set -e
          echo "[create-edb-operator-pullsecret-from-vault] Stub job running..."
          echo "Mounted edb-repos2-token contents:"
          ls -l /edb || true
          if [ -f "/edb/token" ]; then
            echo "--- token ---"
            cat "/edb/token"
            echo
          fi
          echo
          echo "TODO: replace this script with logic that creates an EDB pull secret"
          echo "named 'edb-operator-pullsecret-from-vault' in this namespace."
        volumeMounts:
        - name: edb-token
          mountPath: /edb
