apiVersion: v1
kind: Service
metadata:
  name: postgres-primary
  namespace: rhsi
spec:
  selector:
    app: postgres-primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
