apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: skupper-operator
  namespace: skupper-operator
spec:
  channel: stable
  name: skupper-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
