apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: edb-site-b
  namespace: db
  labels:
    app: edb-site-b
spec:
  instances: 1

  imageName: docker.enterprisedb.com/k8s/postgresql:16-standard-ubi9

  superuserSecret:
    name: edb-site-b-superuser

  bootstrap:
    initdb:
      database: postgres
      owner: postgres

  storage:
    size: 20Gi
    storageClass: REPLACE_WITH_STORAGE_CLASS

  postgresql:
    parameters:
      wal_level: logical
      max_replication_slots: "10"
      max_wal_senders: "10"

  # External reference to the remote site-a cluster, reached via Skupper
  externalClusters:
    - name: site-a
      connectionParameters:
        host: pg-site-a.rhsi.svc.cluster.local
        user: postgres
        dbname: postgres
      password:
        name: edb-site-b-superuser
        key: password

