apiVersion: batch/v1
kind: Job
metadata:
  name: edb-site-b-init
  namespace: db
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init
          image: registry.access.redhat.com/ubi9/ubi-minimal:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              microdnf install -y postgresql &&                   export PGPASSWORD="${PGPASSWORD}" &&                   psql "host=edb-site-b-rw.db.svc.cluster.local dbname=postgres user=postgres" <<'SQL'
              CREATE TABLE IF NOT EXISTS site_b_data (
                id         serial PRIMARY KEY,
                site       text DEFAULT 'site-b',
                payload    text,
                created_at timestamptz DEFAULT now()
              );
              SQL
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: edb-site-b-superuser
                  key: password

