apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg-standby
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pg-standby
  template:
    metadata:
      labels:
        app: pg-standby
    spec:
      containers:
        - name: postgres
          image: bitnami/postgresql-repmgr:15
          imagePullPolicy: IfNotPresent
          env:
            - name: POSTGRESQL_POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-standby-auth
                  key: postgres-password
            - name: REPMGR_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-standby-auth
                  key: repmgr-password
            - name: REPMGR_PRIMARY_HOST
              value: pg-primary.rhsi.svc.cluster.local
            - name: REPMGR_PRIMARY_PORT
              value: "5432"
            - name: REPMGR_NODE_NAME
              value: pg-standby
            - name: REPMGR_NODE_NETWORK_NAME
              value: pg-standby.db.svc.cluster.local
            - name: REPMGR_PARTNER_NODES
              value: pg-primary.rhsi.svc.cluster.local,pg-standby.db.svc.cluster.local
            - name: POSTGRESQL_REPLICATION_MODE
              value: replica
            - name: POSTGRESQL_REPLICA_PRIORITY
              value: "100"
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: data
              mountPath: /bitnami/postgresql
      volumes:
        - name: data
          emptyDir: {}
