apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Cluster
metadata:
  name: edb-site-a
  namespace: db
  labels:
    app: edb-site-a
spec:
  instances: 1

  imageName: docker.enterprisedb.com/k8s/postgresql:16-standard-ubi9

  superuserSecret:
    name: edb-site-a-superuser

  bootstrap:
    initdb:
      database: postgres
      owner: postgres

  storage:
    size: 20Gi
    storageClass: REPLACE_WITH_STORAGE_CLASS

  postgresql:
    parameters:
      wal_level: logical
      max_replication_slots: "10"
      max_wal_senders: "10"

  externalClusters:
    - name: site-b
      connectionParameters:
        host: edb-site-b.rhsi.svc.cluster.local
        user: postgres
        dbname: postgres
      password:
        name: edb-site-a-superuser
        key: password

