apiVersion: postgresql.k8s.enterprisedb.io/v1
kind: Subscription
metadata:
  name: site-b-to-site-a-sub
  namespace: db
spec:
  cluster:
    name: edb-site-a
  dbname: postgres
  name: site_b_sub
  externalClusterName: site-b
  publicationName: site_b_pub
  subscriptionReclaimPolicy: delete

