apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhsi-operator-group
  namespace: openshift-operators
spec:
  targetNamespaces:
  - openshift-operators
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: red-hat-service-interconnect
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: red-hat-service-interconnect
  source: redhat-operators
  sourceNamespace: openshift-marketplace
