apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: rhsi-standby
  namespace: openshift-gitops
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: rhsi-role
              operator: In
              values:
                - standby
